--CREATE DATABASE BRSEGM;
--GO;

--USE BRSEGM;
--GO;

CREATE TABLE ACREEDORDEFAULT
   (	ID INT IDENTITY PRIMARY KEY, 
	IDENTIFICACION VARCHAR(20), 
	NOMBREINSTITUCION VARCHAR(200), 
	MUNICIPIO VARCHAR(30), 
	DOMICILIO VARCHAR(300), 
	CORREO VARCHAR(50), 
	TELEFONO VARCHAR(20), 
	NACIONAL VARCHAR(20), 
	USUARIOCREADOR VARCHAR(20), 
	FECHACREADO DATETIME DEFAULT GETDATE(), 
	USUARIOMODIFICADOR VARCHAR(20), 
	FECHAMODIFICADO DATETIME, 
	STATUS INT DEFAULT 1
   )


   CREATE TABLE ACREEDORES 
   (	IDACREEDOR INT IDENTITY PRIMARY KEY, 
	RNCCEDULA VARCHAR(20 ), 
	NOMBREACREEDOR VARCHAR(255 ), 
	IDMUNICIPIO VARCHAR(50 ), 
	DOMICILIO VARCHAR(255 ), 
	CORREOELECTRONICO VARCHAR(255 ), 
	TELEFONO VARCHAR(20 ), 
	NACIONAL VARCHAR(20 ), 
	FECHAEXCLUSION VARCHAR(20 ), 
	IDINSCRIPCION INT
   )

   CREATE TABLE BIENES 
	(	IDBIEN INT IDENTITY PRIMARY KEY, 
		IDTIPOPROPIEDAD INT, 
		IDTIPOBIEN INT, 
		NUMEROSERIAL VARCHAR(50), 
		DESCRIPCIONBIEN VARCHAR(255), 
		INCORPORACIONINMUEBLE VARCHAR(20), 
		INCORPORACIONINMUEBLEDESCRIPCION VARCHAR(255), 
		INCORPORACIONINMUEBLEMATRICULA VARCHAR(255), 
		INCORPORACIONINMUEBLEDISTRITOCATASTRAL VARCHAR(255), 
		INCORPORACIONINMUEBLENUMEROPARCELA VARCHAR(255), 
		REGISTRODONDESEENCUENTRAINSCRITO VARCHAR(255), 
		UBICACIONDELINMUEBLE VARCHAR(255), 
		FECHAEXCLUSION VARCHAR(20), 
		IDINSCRIPCION INT
	)

   CREATE TABLE CLIENTESSEGM
   (	ID_CLIENTE INT PRIMARY KEY, 
	IDENTIFICACION VARCHAR(11), 
	TIPOIDENTIFICACION VARCHAR(15), 
	NOMBRE_CLIENTE VARCHAR(60), 
	FECHA_INGRESADO DATETIME DEFAULT GETDATE(), 
	FECHA_MODIFICADO VARCHAR(20), 
	USUARIO VARCHAR(30)
   )

   CREATE TABLE DEUDORES 
   (	IDDEUDOR INT IDENTITY PRIMARY KEY , 
	IDTIPODEUDOR INT, 
	RNCCEDULA VARCHAR(20), 
	NOMBREDEUDOR VARCHAR(255), 
	IDMUNICIPIO VARCHAR(50), 
	DOMICILIO VARCHAR(255), 
	CORREOELECTRONICO VARCHAR(255), 
	TELEFONO VARCHAR(20), 
	NACIONAL VARCHAR(20), 
	IDINSCRIPCION INT
   )

   CREATE TABLE REGISTROINSCRIPCION
   (	IDINSCRIPCION INT IDENTITY PRIMARY KEY, 
	NUMERO_REGISTRO_MICM INT, 
	ESTADO_MICM INT, 
	ESTADO_BR INT DEFAULT 0, 
	NUMERO_SP VARCHAR(50 ), 
	USUARIOCREADOR VARCHAR(255), 
	FECHACREACION DATETIME DEFAULT GETDATE(), 
	USUARIOMODIFICADOR VARCHAR(255), 
	FECHAMODIFICACION DATETIME
   )

   CREATE TABLE DOCUMENTOSSEGM 
   (	IDDOC INT IDENTITY PRIMARY KEY, 
	NOMBREDOC VARCHAR(100), 
	USERUP VARCHAR(100), 
	FECHAIMPORT DATE, 
	HORAIMPORT VARCHAR(20), 
	FECHAPROCESS VARCHAR(50), 
	CANTIDADREGISTRO INT, 
	ESTADO INT DEFAULT 0, 
	REGISTROSPROCESADOS INT DEFAULT NULL, 
	MENSAGE VARCHAR(4000), 
	REGISTROSNOPROCESADOS INT
   )

   CREATE TABLE GARANTIAS_PROXIMAS_VENCER
   (	ID INT IDENTITY PRIMARY KEY, 
	NUMERO_REGISTRO_MICM INT, 
	NOMBRE_DEL_CLIENTE VARCHAR(100), 
	IDENTIFICACION_CLIENTE VARCHAR(20), 
	FECHA_VENCIMIENTO VARCHAR(50), 
	NUMERO_BIEN VARCHAR(4000), 
	NUMERO_SP VARCHAR(30), 
	ESTADO VARCHAR(20), 
	MONEDA VARCHAR(10), 
	MONTO DECIMAL, 
	NOTIFICAR INT DEFAULT 1, 
	FECHAREGISTRADO DATETIME DEFAULT GETDATE(), 
	FECHAMODIFICADO DATE
   )

   CREATE TABLE LOGERRORESREGISTROS
   (	IDDOC INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(4000 ), 
	FECHA VARCHAR(30)
   )

   CREATE TABLE LOGSEGM 
   (	ID_LOG INT IDENTITY PRIMARY KEY, 
	ORIGEN VARCHAR(50) NOT NULL, 
	TIPO VARCHAR(10) NOT NULL, 
	FECHA DATE, 
	HORA VARCHAR(20), 
	DESCRIPCION VARCHAR(4000) NOT NULL, 
	COMENTARIO VARCHAR(4000), 
	USUARIO VARCHAR(50)
   )

   CREATE TABLE MUNICIPIOSEGM 
   (	IDM INT IDENTITY PRIMARY KEY, 
	IDMUNICIPIO VARCHAR(20), 
	MUNICIPIO VARCHAR(100) NOT NULL, 
	PROVINCIA VARCHAR(100) NOT NULL
   ) 

   CREATE TABLE OPERACIONES 
   (	IDOPERACIONES INT IDENTITY PRIMARY KEY, 
	IDTIPOAVISOINSCRIPCION INT, 
	TIPOCONCILIACION INT, 
	FECHAVENCIMIENTO VARCHAR(20), 
	COMENTARIOS VARCHAR(500), 
	MONEDA VARCHAR(50), 
	MONTO DECIMAL, 
	TIPODEGARANTIAMOBILIARIO INT, 
	IDTIPOEMBARGO INT, 
	ESTADOEMBARGONODISPADMJUD VARCHAR(255), 
	EJECUCIONDESCRIPCIONOBLIGACIONGARANTIZADA VARCHAR(255), 
	EJECUCIONDESCRIPCIONINCUMPLIMIENTODEUDOR VARCHAR(255), 
	EJECUCIONDESCRIPCIONPRUEBAINCUMPLIMIENTO VARCHAR(255), 
	EJECUCIONDESCRIPCIONMONTOSALDO INT, 
	EJECUCIONDESCRIPCIONMONTOFIJADO INT, 
	EJECUCIONCOSTAPROCESALES INT, 
	SUCURSALLEY VARCHAR(50), 
	OTRO VARCHAR(255), 
	IDINSCRIPCION INT
   )

   CREATE TABLE REGISTROSGARANTIAMOBILIARIA 
   (	IDDOC INT, 
	IDTIPOAVISOINSCRIPCION INT, 
	TIPOCONCILIACION INT, 
	FECHAVENCIMIENTO VARCHAR(50), 
	COMENTARIOS VARCHAR(370), 
	MONEDA VARCHAR(3), 
	MONTO INT, 
	TIPODEGARANTIAMOBILIARIO INT, 
	RNCCEDULAACREE INT, 
	NOMBREACREEDOR VARCHAR(200), 
	IDMUNICIPIOACREE VARCHAR(50), 
	DOMICILIOACREE VARCHAR(200), 
	CORREOELECTRONICOACREE VARCHAR(50), 
	TELEFONOACREE VARCHAR(20), 
	NACIONALACREEDOR INT, 
	RNCCEDULADEUDOR VARCHAR(100), 
	IDTIPODEUDOR VARCHAR(20), 
	NOMBREDEUDOR VARCHAR(300), 
	IDMUNICIPIODEUDOR VARCHAR(200), 
	DOMICILIODEUDOR VARCHAR(500), 
	CORREOELECTRONICODEUDOR VARCHAR(200), 
	TELEFONODEUDOR VARCHAR(200), 
	NACIONALDEUDOR VARCHAR(20), 
	NUMEROSERIAL VARCHAR(100), 
	IDTIPOPROPIEDAD INT, 
	IDTIPOBIEN INT, 
	DESCRIPCIONBIEN VARCHAR(500), 
	INCORPORACIONINMUEBLE INT, 
	INCINMUEBLEDESCRIPCION VARCHAR(300), 
	RDSEINSCRITO VARCHAR(100), 
	UBICACIONDELINMUEBLE VARCHAR(200), 
	IDAPI INT, 
	ESTADO_R INT, 
	ID_R INT NOT NULL, 
	NUMERO_SP VARCHAR(200), 
	IDTIPOEMBARGO INT, 
	ESTADOEMBARGONODISPADMJUD VARCHAR(200), 
	EJECUCIONDESCRIPCIONOBLIGACIONGARANTIZADA VARCHAR(2000), 
	EJECUCIONDESCRIPCIONINCUMPLIMIENTODEUDOR VARCHAR(2000), 
	EJECUCIONDESCRIPCIONPRUEBAINCUMPLIMIENTO VARCHAR(2000), 
	EJECUCIONDESCRIPCIONMONTOSALDO INT, 
	EJECUCIONCOSTAPROCESALES INT, 
	INCORPORACIONINMUEBLEMATRICULA VARCHAR(500), 
	INCORPORACIONINMUEBLEDISTRITOCATASTRAL VARCHAR(500), 
	INCORPORACIONINMUEBLENUMEROPARCELA VARCHAR(500), 
	FECHAEXCLUSION DATETIME, 
	EJECUTADO INT, 
	NUMERO_REGISTRO_EMBARGO INT, 
	EJECUCIONDESCRIPCIONMONTOFIJO INT
   )

   CREATE TABLE ROLES 
   (	ID_ROL INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(30), 
	PERMISO_LECTURA INT, 
	PERMISO_ESCRITURA INT, 
	PERMISO_VALIDACION INT, 
	PERMISO_MODIFICACION INT, 
	PERMISO_PROCESAR INT, 
	ESTADO INT DEFAULT 1, 
	USUARIOCREADOR VARCHAR(255), 
	FECHACREACION DATETIME DEFAULT GETDATE(), 
	USUARIOMODIFICADOR VARCHAR(255), 
	FECHAMODIFICACION DATETIME
   )

   CREATE TABLE SEGM_NOTIFICACION 
   (	ID INT IDENTITY PRIMARY KEY, 
	DESTINATARIOS VARCHAR(1000), 
	ESTADO BIT DEFAULT 1, 
	FRECUENCIA INT DEFAULT 1, 
	DIASPROXIMOVENCER INT DEFAULT 15, 
	MENSAJE VARCHAR(4000), 
	FECHA_MODIFICACION DATETIME DEFAULT GETDATE(), 
	USUARIO VARCHAR(20)
   )

   CREATE TABLE SEGM_PARAMETROS 
   (	ID_KEY INT, 
	TIPO INT NOT NULL, 
	VALOR NVARCHAR(1000) NOT NULL, 
	NOMBRECLAVE VARCHAR(50), 
	DESCRIPCION NVARCHAR(200), 
	ESTADO BIT NOT NULL, 
	ID_USO INT, 
	USUARIO VARCHAR(20), 
	FECHACREACION DATETIME NOT NULL, 
	FECHAMODIFICACION DATETIME
   )

   CREATE TABLE SEGM_PROCESO 
   (	ID INT IDENTITY PRIMARY KEY, 
	NOMBRE_PROCESO VARCHAR(100), 
	ESTADO BIT, 
	USUARIO_CUENTA VARCHAR(50), 
	CONTRA_CUENTA VARCHAR(50), 
	FECHA_MODIFICACION DATETIME DEFAULT GETDATE(), 
	USUARIO VARCHAR(20)
   )

   CREATE TABLE TIPO_CONCILIACION 
   (	ID_TIPO_CONCILIACION INT, 
	DESCRIPCION VARCHAR(20), 
	ESTADO BIT DEFAULT 1, 
	USUARIO_CREADOR VARCHAR(20), 
	FECHA_CREADO DATETIME DEFAULT GETDATE(), 
	USUARIO_MODIFICADOR VARCHAR(20), 
	FECHA_MODIFICADO DATETIME
   )

   CREATE TABLE TIPO_GARANTIA 
   (	ID_TIPO_GARANTIA INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(100), 
	ESTADO INT DEFAULT 1, 
	USUARIO_CREADOR VARCHAR(20), 
	FECHA_CREADO DATETIME DEFAULT GETDATE(), 
	USUARIO_MODIFICADOR VARCHAR(20), 
	FECHA_MODIFICADO DATETIME
   )

   CREATE TABLE TIPOBIENSEGM 
   (	IDTIPOBIEN INT IDENTITY PRIMARY KEY, 
		DESCRIPCION VARCHAR(50) NOT NULL
   )

   CREATE TABLE TIPOS_AVISOS_INSCRIPCION 
   (	ID_TIPO_AVISO INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(200), 
	ESTADO INT DEFAULT 1, 
	USUARIO_CREADOR VARCHAR(20), 
	FECHA_CREADO DATETIME DEFAULT GETDATE(), 
	USUARIO_MODIFICADOR VARCHAR(20), 
	FECHA_MODIFICADO DATETIME
   )

   CREATE TABLE TIPOS_DEUDORES 
   (	ID_TIPO_DEUDOR INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(30), 
	ESTADO INT DEFAULT 1, 
	USUARIO_CREADOR VARCHAR(20), 
	FECHA_CREADO DATETIME DEFAULT GETDATE(), 
	USUARIO_MODIFICADOR VARCHAR(20), 
	FECHA_MODIFICADO DATETIME
   )

   CREATE TABLE TIPOS_EMBARGOS 
   (	ID_TIPO_EMBARGO INT IDENTITY PRIMARY KEY, 
	DESCRIPCION VARCHAR(50), 
	ESTADO INT DEFAULT 1, 
	USUARIO_CREADOR VARCHAR(20), 
	FECHA_CREADO DATETIME DEFAULT GETDATE(), 
	USUARIO_MODIFICADOR VARCHAR(20), 
	FECHA_MODIFICADO DATETIME
   )

   CREATE TABLE USUARIOS 
   (	ID_USER INT IDENTITY PRIMARY KEY, 
	USUARIO VARCHAR(30), 
	ID_ROL INT, 
	ESTADO INT DEFAULT 1, 
	USUARIOCREADOR VARCHAR(255), 
	FECHACREACION DATETIME DEFAULT GETDATE(), 
	USUARIOMODIFICADOR VARCHAR(255), 
	FECHAMODIFICACION DATETIME
   )

      ALTER TABLE DEUDORES ADD CONSTRAINT FK_REGISTROINSCRIPCION_DEUDORES FOREIGN KEY (IDINSCRIPCION)
	  REFERENCES REGISTROINSCRIPCION (IDINSCRIPCION)

   	  ALTER TABLE BIENES ADD CONSTRAINT FK_REGISTROINSCRIPCION_BIENES FOREIGN KEY (IDINSCRIPCION)
	  REFERENCES REGISTROINSCRIPCION (IDINSCRIPCION);

	  ALTER TABLE OPERACIONES ADD CONSTRAINT FK_REGISTROINSCRIPCION_OPERACIONES FOREIGN KEY (IDINSCRIPCION)
	  REFERENCES REGISTROINSCRIPCION (IDINSCRIPCION)

	  ALTER TABLE USUARIOS ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROL)
	  REFERENCES ROLES (ID_ROL);